### ISSUE TITLE
Idea: Incorporate provision for AWS Lambda

### ISSUE THREAD

**Issue by shafqatevo** [madebyhiro/codem-transcode#37]
Hi there,

AWS Lambda seems to be a perfect solution for indefinitely scalable processing jobs like ffmpeg transcoding. They already mention node-ffmpeg in their documentation. This will be great if there's a version of codem which runs in Lambda and acts when source videos are uploaded into S3, processes it and puts the resulting video in another bucket.

Thanks!
Shafqat

**Comment by tieleman** [comment]
Looks interesting, I'll check AWS Lambda out some time!

**Comment by tieleman** [comment]
Upon further investigation (yes, a bit late, sorry), it seems that AWS Lambda is not really suited for this kind of task. In their own documentation/FAQ they mention that tasks need to finish in 60 seconds or less and that you only get 500MB of scratch space to perform your task. Also, you have no control over compute power. This will only make it suitable for very small encoding jobs and not really for general purpose transcoding. So I'm closing this suggestion for now, thanks!
