### ISSUE TITLE
Transcoding file streams

### ISSUE THREAD

**Issue by switz** [madebyhiro/codem-transcode#43]
I'm building a file uploader on top of codem-transcode. Is it possible to send a file stream to codem-transcode for on-the-fly transcoding?

Relevant links:
http://stackoverflow.com/a/28400589/240569
https://github.com/trenskow/stream-transcoder.js

**Comment by tieleman** [comment]
Sorry for the late comment, this one must have slipped by. No, it is not possible at this time. However, you could probably initiate a file-based stream from your software and then supply that file as input to codem-transcode for a job.
