### ISSUE TITLE
External mysql2 connection

### ISSUE THREAD

**Issue by ProvostA** [madebyhiro/codem-transcode#44]
When i try to configure the config file for an external mysql server, i got the error
"You need to install mysql package manually" when i start the codem-transcode server

{
    "port":            8080,
    "access_log":      "/var/log/access_log",
    "database":        {
        "dialect": "mysql",
        "username": "root",        
        "database": "codem",
        "host": "IP adress of my external server",
        "port": 3306
   },
    "slots":           8,
    "interface":       "127.0.0.1",
    "encoder":         "ffmpeg",
    "scratch_dir":     "/tmp",
    "use_scratch_dir": true,
    "ffprobe":         null
}

**Comment by tieleman** [comment]
Did you install the mysql package using npm (either in the codem-transcode node_modules directory, or globally)?

    # npm install mysql

**Comment by ProvostA** [comment]
Hi Sjoerd ,

Thank you for fast tracking

I tried to install it in node_modules and falsehood has vanished.

Now I have to learn how to specify the password in the config file
There is no mention in the documentation about it. I tried different possibilities , without success.
Could you give me the name of the parameter ?



[_MG_9367]
Alain Provost
Responsable technique
Production audiovisuelle et multimédia
[courriel]<http://www.audiovisuel.uqam.ca/>
514.987.3000  poste 7683
Télécopieur : 514.987.4820

De : Sjoerd Tieleman [mailto:notifications@github.com]
Envoyé : vendredi 19 juin 2015 03:15
À : madebyhiro/codem-transcode
Cc : Provost, Alain
Objet : Re: [codem-transcode] External mysql2 connection (#44)


Did you install the mysql package using npm (either in the codem-transcode node_modules directory, or globally)?

# npm install mysql

**Comment by ProvostA** [comment]
Hi Sjoerd,

Sorry, i found the problem. I did a typo in the config file.

All is fine now


[_MG_9367]
Alain Provost
Responsable technique
Production audiovisuelle et multimédia
[courriel]<http://www.audiovisuel.uqam.ca/>
514.987.3000  poste 7683
Télécopieur : 514.987.4820

De : Sjoerd Tieleman [mailto:notifications@github.com]
Envoyé : vendredi 19 juin 2015 03:15
À : madebyhiro/codem-transcode
Cc : Provost, Alain
Objet : Re: [codem-transcode] External mysql2 connection (#44)


Did you install the mysql package using npm (either in the codem-transcode node_modules directory, or globally)?

# npm install mysql

**Comment by tieleman** [comment]
Good to hear, thanks!
