### ISSUE TITLE
-ss and or -t should be before -i

### ISSUE THREAD

**Issue by scottf-tvw** [madebyhiro/codem-transcode#56]
if -ss is used in options, it should be placed before the input file as per the documentation for seek on the **input file**. Finding and extracting -ss would be needed in the jobs.js file and pushed into the string before -i. This can solve issues with mp4 files audio and video sync issues on long format videos.

**Comment by scottf-tvw** [comment]
added fix and made pull request.

**Comment by tieleman** [comment]
Thank you! I've pulled #57.
