### ISSUE TITLE
ffmpeg stderr buffer size

### ISSUE THREAD

**Issue by bartzon** [madebyhiro/codem-transcode#59]
Looks like ffmpeg can report more on stderr than node's maxBuffer is expecting. See http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process for a similar type of error. This causes the ffmpeg process to finish with an error, and therefore the transcoding fails. 

Could you take a look at this? Thanks!

**Comment by tieleman** [comment]
This commit (https://github.com/madebyhiro/codem-transcode/commit/eb6114fe49374a550ad8570392482b30f2ecde2b) already increases the buffer to 4MB. Not enough? We could increase it.
