### ISSUE TITLE
v.1.0-alpha: job failed processing with bunyan usage error

### ISSUE THREAD

**Issue by Grid405** [madebyhiro/codem-transcode#65]
codem-transcode accepts the job, but then fails with "bunyan usage error":

bunyan usage error: C:\Users\Grid405\AppData\Roaming\npm\node_modules\codem-transcode\lib\request_handler.js:171: attempt to log with an unbound log method: `this` is: RequestHandler {
  _logger:
   Logger {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     _level: 30,
     streams: [ [Object] ],
     serializers: { req: [Function: req], res: [Function: res] },
     src: false,
     fields: { name: 'codem-transcode', hostname: 'Grid405-PC', pid: 8888 },
     haveNonRawStreams: true },
  _storageBackend:
   MemoryStorageBackend {
     _cache:
      LRUCache {
        size: 1,
        limit: 500,
        _keymap: [Object],
        head: [Object],
        tail: [Object] } },
  _totalAvailableSlots: 4,
  _processorBackends: Map { 'codem-ffmpeg' => [Function: FFmpeg] },
  _processors:
   Map {
     'eee1c0f889a976ac5eeb9040f185a44010a05196' => FFmpeg {
     domain: null,
     _events: [Object],
     _eventsCount: 4,
     _maxListeners: undefined,
     _args: [Object],
     _childProcess: [Object],
     _output: '' } } }
{"name":"codem-transcode","hostname":"Grid405-PC","pid":8888,"level":30,"context":{"exitCode":1,"id":"eee1c0f889a976ac5eeb9040f185a44010a05196"},"msg":"Job failed processing.","time":"2017-04-19T13:27:33.489Z","v":0}

**Comment by yliharma** [comment]
Same error here....have you found out anything?

**Comment by Grid405** [comment]
Nope, i ended up using v.0.5.11

**Comment by yliharma** [comment]
Which doesn't work with hwaccel option which has to go before the input file ... :cry:

**Comment by yliharma** [comment]
I've found out that the bunyan error is only a warning (non blocking) since version 1.2.4 [https://github.com/trentm/node-bunyan/blob/master/CHANGES.md#124](url) so the failing job is due to something else.
